# Generated by Django 2.2 on 2021-06-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210608_1234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='groups_orgs',
        ),
    ]
